// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: proto/createmem.proto

package protocreatemem

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CreatememServiceClient is the client API for CreatememService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreatememServiceClient interface {
	//Создание записи
	Create(ctx context.Context, in *CreateMemRequest, opts ...grpc.CallOption) (*CreateMemResponse, error)
}

type creatememServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCreatememServiceClient(cc grpc.ClientConnInterface) CreatememServiceClient {
	return &creatememServiceClient{cc}
}

func (c *creatememServiceClient) Create(ctx context.Context, in *CreateMemRequest, opts ...grpc.CallOption) (*CreateMemResponse, error) {
	out := new(CreateMemResponse)
	err := c.cc.Invoke(ctx, "/pb.CreatememService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreatememServiceServer is the server API for CreatememService service.
// All implementations must embed UnimplementedCreatememServiceServer
// for forward compatibility
type CreatememServiceServer interface {
	//Создание записи
	Create(context.Context, *CreateMemRequest) (*CreateMemResponse, error)
	mustEmbedUnimplementedCreatememServiceServer()
}

// UnimplementedCreatememServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCreatememServiceServer struct {
}

func (UnimplementedCreatememServiceServer) Create(context.Context, *CreateMemRequest) (*CreateMemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCreatememServiceServer) mustEmbedUnimplementedCreatememServiceServer() {}

// UnsafeCreatememServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreatememServiceServer will
// result in compilation errors.
type UnsafeCreatememServiceServer interface {
	mustEmbedUnimplementedCreatememServiceServer()
}

func RegisterCreatememServiceServer(s grpc.ServiceRegistrar, srv CreatememServiceServer) {
	s.RegisterService(&CreatememService_ServiceDesc, srv)
}

func _CreatememService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreatememServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CreatememService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreatememServiceServer).Create(ctx, req.(*CreateMemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreatememService_ServiceDesc is the grpc.ServiceDesc for CreatememService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreatememService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CreatememService",
	HandlerType: (*CreatememServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CreatememService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/createmem.proto",
}
