// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.1
// source: proto/createmem.proto

package protocreatemem

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//------------------------------------------------------------------------------------------------------------------
//  CREATE
//------------------------------------------------------------------------------------------------------------------
type CreateMemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentId string `protobuf:"bytes,1,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId   string `protobuf:"bytes,3,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Content  string `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *CreateMemRequest) Reset() {
	*x = CreateMemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_createmem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemRequest) ProtoMessage() {}

func (x *CreateMemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_createmem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemRequest.ProtoReflect.Descriptor instead.
func (*CreateMemRequest) Descriptor() ([]byte, []int) {
	return file_proto_createmem_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMemRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateMemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateMemRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CreateMemRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateMemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Memcreate *Memcreate `protobuf:"bytes,1,opt,name=Memcreate,proto3" json:"Memcreate,omitempty"`
}

func (x *CreateMemResponse) Reset() {
	*x = CreateMemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_createmem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemResponse) ProtoMessage() {}

func (x *CreateMemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_createmem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemResponse.ProtoReflect.Descriptor instead.
func (*CreateMemResponse) Descriptor() ([]byte, []int) {
	return file_proto_createmem_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMemResponse) GetMemcreate() *Memcreate {
	if x != nil {
		return x.Memcreate
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  COMMENT
//------------------------------------------------------------------------------------------------------------------
type Memcreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slug     string `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	ParentId string `protobuf:"bytes,2,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	UserId   string `protobuf:"bytes,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId   string `protobuf:"bytes,4,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Content  string `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	Status   int32  `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *Memcreate) Reset() {
	*x = Memcreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_createmem_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Memcreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memcreate) ProtoMessage() {}

func (x *Memcreate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_createmem_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memcreate.ProtoReflect.Descriptor instead.
func (*Memcreate) Descriptor() ([]byte, []int) {
	return file_proto_createmem_proto_rawDescGZIP(), []int{2}
}

func (x *Memcreate) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Memcreate) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Memcreate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Memcreate) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Memcreate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Memcreate) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_proto_createmem_proto protoreflect.FileDescriptor

var file_proto_createmem_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x6d, 0x65,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x78, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x40, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x4d, 0x65, 0x6d, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x4d, 0x65, 0x6d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x09, 0x4d, 0x65, 0x6d, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x09, 0x4d, 0x65, 0x6d, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x53, 0x6c, 0x75, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x50,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6f, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x61, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x6d,
	0x65, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x22, 0x0e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6d, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6d, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_createmem_proto_rawDescOnce sync.Once
	file_proto_createmem_proto_rawDescData = file_proto_createmem_proto_rawDesc
)

func file_proto_createmem_proto_rawDescGZIP() []byte {
	file_proto_createmem_proto_rawDescOnce.Do(func() {
		file_proto_createmem_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_createmem_proto_rawDescData)
	})
	return file_proto_createmem_proto_rawDescData
}

var file_proto_createmem_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_createmem_proto_goTypes = []interface{}{
	(*CreateMemRequest)(nil),  // 0: pb.CreateMemRequest
	(*CreateMemResponse)(nil), // 1: pb.CreateMemResponse
	(*Memcreate)(nil),         // 2: pb.Memcreate
}
var file_proto_createmem_proto_depIdxs = []int32{
	2, // 0: pb.CreateMemResponse.Memcreate:type_name -> pb.Memcreate
	0, // 1: pb.CreatememService.Create:input_type -> pb.CreateMemRequest
	1, // 2: pb.CreatememService.Create:output_type -> pb.CreateMemResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_createmem_proto_init() }
func file_proto_createmem_proto_init() {
	if File_proto_createmem_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_createmem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_createmem_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_createmem_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Memcreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_createmem_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_createmem_proto_goTypes,
		DependencyIndexes: file_proto_createmem_proto_depIdxs,
		MessageInfos:      file_proto_createmem_proto_msgTypes,
	}.Build()
	File_proto_createmem_proto = out.File
	file_proto_createmem_proto_rawDesc = nil
	file_proto_createmem_proto_goTypes = nil
	file_proto_createmem_proto_depIdxs = nil
}
