// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.1
// source: proto/getmem.proto

package protogetmem

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//------------------------------------------------------------------------------------------------------------------
//  GET
//------------------------------------------------------------------------------------------------------------------
type GetMemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slug string `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
}

func (x *GetMemRequest) Reset() {
	*x = GetMemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_getmem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemRequest) ProtoMessage() {}

func (x *GetMemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getmem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemRequest.ProtoReflect.Descriptor instead.
func (*GetMemRequest) Descriptor() ([]byte, []int) {
	return file_proto_getmem_proto_rawDescGZIP(), []int{0}
}

func (x *GetMemRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetMemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mem *Mem `protobuf:"bytes,1,opt,name=Mem,proto3" json:"Mem,omitempty"`
}

func (x *GetMemResponse) Reset() {
	*x = GetMemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_getmem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemResponse) ProtoMessage() {}

func (x *GetMemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getmem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemResponse.ProtoReflect.Descriptor instead.
func (*GetMemResponse) Descriptor() ([]byte, []int) {
	return file_proto_getmem_proto_rawDescGZIP(), []int{1}
}

func (x *GetMemResponse) GetMem() *Mem {
	if x != nil {
		return x.Mem
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  COMMENT
//------------------------------------------------------------------------------------------------------------------
type Mem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slug     string `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	ParentId string `protobuf:"bytes,2,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	UserId   string `protobuf:"bytes,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PostId   string `protobuf:"bytes,4,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Content  string `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	Status   int32  `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *Mem) Reset() {
	*x = Mem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_getmem_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mem) ProtoMessage() {}

func (x *Mem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getmem_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mem.ProtoReflect.Descriptor instead.
func (*Mem) Descriptor() ([]byte, []int) {
	return file_proto_getmem_proto_rawDescGZIP(), []int{2}
}

func (x *Mem) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Mem) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Mem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Mem) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Mem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Mem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_proto_getmem_proto protoreflect.FileDescriptor

var file_proto_getmem_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x74, 0x6d, 0x65, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x6c, 0x75, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53, 0x6c, 0x75, 0x67, 0x22, 0x2b, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a,
	0x03, 0x4d, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e,
	0x4d, 0x65, 0x6d, 0x52, 0x03, 0x4d, 0x65, 0x6d, 0x22, 0x97, 0x01, 0x0a, 0x03, 0x4d, 0x65, 0x6d,
	0x12, 0x12, 0x0a, 0x04, 0x53, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x53, 0x6c, 0x75, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74,
	0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x32, 0x59, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x6d, 0x65, 0x6d, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x67, 0x65, 0x74, 0x2f, 0x7b, 0x53, 0x6c, 0x75, 0x67, 0x7d, 0x42, 0x1e, 0x5a,
	0x1c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x6d, 0x65,
	0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x74, 0x6d, 0x65, 0x6d, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_getmem_proto_rawDescOnce sync.Once
	file_proto_getmem_proto_rawDescData = file_proto_getmem_proto_rawDesc
)

func file_proto_getmem_proto_rawDescGZIP() []byte {
	file_proto_getmem_proto_rawDescOnce.Do(func() {
		file_proto_getmem_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_getmem_proto_rawDescData)
	})
	return file_proto_getmem_proto_rawDescData
}

var file_proto_getmem_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_getmem_proto_goTypes = []interface{}{
	(*GetMemRequest)(nil),  // 0: pb.GetMemRequest
	(*GetMemResponse)(nil), // 1: pb.GetMemResponse
	(*Mem)(nil),            // 2: pb.Mem
}
var file_proto_getmem_proto_depIdxs = []int32{
	2, // 0: pb.GetMemResponse.Mem:type_name -> pb.Mem
	0, // 1: pb.GetmemService.Get:input_type -> pb.GetMemRequest
	1, // 2: pb.GetmemService.Get:output_type -> pb.GetMemResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_getmem_proto_init() }
func file_proto_getmem_proto_init() {
	if File_proto_getmem_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_getmem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_getmem_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_getmem_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_getmem_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_getmem_proto_goTypes,
		DependencyIndexes: file_proto_getmem_proto_depIdxs,
		MessageInfos:      file_proto_getmem_proto_msgTypes,
	}.Build()
	File_proto_getmem_proto = out.File
	file_proto_getmem_proto_rawDesc = nil
	file_proto_getmem_proto_goTypes = nil
	file_proto_getmem_proto_depIdxs = nil
}
