// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: proto/getmem.proto

package protogetmem

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetmemServiceClient is the client API for GetmemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetmemServiceClient interface {
	//Возвращает запись по SLUG
	Get(ctx context.Context, in *GetMemRequest, opts ...grpc.CallOption) (*GetMemResponse, error)
}

type getmemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetmemServiceClient(cc grpc.ClientConnInterface) GetmemServiceClient {
	return &getmemServiceClient{cc}
}

func (c *getmemServiceClient) Get(ctx context.Context, in *GetMemRequest, opts ...grpc.CallOption) (*GetMemResponse, error) {
	out := new(GetMemResponse)
	err := c.cc.Invoke(ctx, "/pb.GetmemService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetmemServiceServer is the server API for GetmemService service.
// All implementations must embed UnimplementedGetmemServiceServer
// for forward compatibility
type GetmemServiceServer interface {
	//Возвращает запись по SLUG
	Get(context.Context, *GetMemRequest) (*GetMemResponse, error)
	mustEmbedUnimplementedGetmemServiceServer()
}

// UnimplementedGetmemServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGetmemServiceServer struct {
}

func (UnimplementedGetmemServiceServer) Get(context.Context, *GetMemRequest) (*GetMemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGetmemServiceServer) mustEmbedUnimplementedGetmemServiceServer() {}

// UnsafeGetmemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetmemServiceServer will
// result in compilation errors.
type UnsafeGetmemServiceServer interface {
	mustEmbedUnimplementedGetmemServiceServer()
}

func RegisterGetmemServiceServer(s grpc.ServiceRegistrar, srv GetmemServiceServer) {
	s.RegisterService(&GetmemService_ServiceDesc, srv)
}

func _GetmemService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetmemServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GetmemService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetmemServiceServer).Get(ctx, req.(*GetMemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetmemService_ServiceDesc is the grpc.ServiceDesc for GetmemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetmemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GetmemService",
	HandlerType: (*GetmemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GetmemService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/getmem.proto",
}
